export const createTicketTable = `
  CREATE TABLE IF NOT EXISTS ticket (
    id BIGSERIAL PRIMARY KEY,
    ticket_number INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    transaction_datetime TIMESTAMPTZ NOT NULL,
    is_lost BOOLEAN NOT NULL DEFAULT FALSE,
    is_stolen BOOLEAN NOT NULL DEFAULT FALSE,
    location TEXT NOT NULL REFERENCES location(location),
    description TEXT NOT NULL,
    due_date TIMESTAMPTZ NOT NULL,
    amount NUMERIC(10, 1) NOT NULL CHECK (amount > 0),
    onetime_fee NUMERIC(10, 1) NOT NULL DEFAULT 0 CHECK (onetime_fee >= 0),
    interest_paid_months INTEGER NOT NULL DEFAULT 0 CHECK (interest_paid_months >= 0),
    partial_payment NUMERIC(10, 2) NOT NULL DEFAULT 0 CHECK (partial_payment >= 0),
    partial_payment_datetime TIMESTAMPTZ DEFAULT NULL,
    interested_datetime TIMESTAMPTZ DEFAULT NULL,
    employee_name TEXT NOT NULL,
    pickup_datetime TIMESTAMPTZ DEFAULT NULL,
    pickup_amount_paid NUMERIC(10, 2) DEFAULT NULL CHECK (pickup_amount_paid IS NULL OR pickup_amount_paid >= 0),
    expire_date TIMESTAMPTZ DEFAULT NULL,
    status TEXT NOT NULL CHECK (status IN ('pawned', 'pawn_expired', 'picked_up', 'sold', 'sell_expired')),
    status_updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    client_number INTEGER REFERENCES client(client_number) ON DELETE SET NULL
  );
`;

export const createTicketIndexes = `
  CREATE INDEX IF NOT EXISTS idx_ticket_pawned_location_due_date
  ON ticket(location, due_date)
  WHERE status = 'pawned';
`;
