export const createTicketTable = `
  CREATE TABLE IF NOT EXISTS ticket (
    id BIGSERIAL PRIMARY KEY,
    ticket_number INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    transaction_datetime TIMESTAMPTZ NOT NULL,
    is_lost BOOLEAN NOT NULL DEFAULT FALSE,
    location TEXT,
    description TEXT,
    due_date TIMESTAMPTZ NOT NULL,
    is_overdue BOOLEAN NOT NULL DEFAULT FALSE,
    amount NUMERIC(10, 1),
    onetime_fee NUMERIC(10, 1),
    interest NUMERIC(5, 1),
    interest_paid_months INTEGER NOT NULL DEFAULT 0,
    pickup_amount NUMERIC(10, 1),
    interested_datetime TIMESTAMPTZ DEFAULT NULL,
    employee_name TEXT,
    pickup_datetime TIMESTAMPTZ DEFAULT NULL,
    expire_date TIMESTAMPTZ DEFAULT NULL,
    status TEXT NOT NULL CHECK (status IN ('pawned', 'pawn_expired', 'picked_up', 'sold', 'sell_expired')),
    status_updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    client_number INTEGER REFERENCES client(client_number) ON DELETE SET NULL,
    items INTEGER[] NOT NULL DEFAULT '{}'
  );
`;

export const createTicketIndexes = `
  CREATE INDEX IF NOT EXISTS idx_ticket_pawned_overdue_location_due_date
  ON ticket(location, due_date)
  WHERE status = 'pawned' AND is_overdue = TRUE;

  CREATE INDEX IF NOT EXISTS idx_ticket_items
  ON ticket USING GIN(items);
`;
