export const createTicketTable = `
  CREATE TABLE IF NOT EXISTS ticket (
    id BIGSERIAL PRIMARY KEY,
    ticket_number INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    transaction_datetime TIMESTAMPTZ NOT NULL,
    is_lost BOOLEAN NOT NULL DEFAULT FALSE,
    location TEXT,
    description TEXT,
    due_date TIMESTAMPTZ NOT NULL,
    is_overdue BOOLEAN NOT NULL DEFAULT FALSE,
    amount NUMERIC(10, 1),
    onetime_fee NUMERIC(10, 1),
    interest NUMERIC(5, 1),
    pickup_amount NUMERIC(10, 1),
    interested_datetime TIMESTAMPTZ DEFAULT NULL,
    employee_name TEXT,
    pickup_datetime TIMESTAMPTZ DEFAULT NULL,
    status TEXT NOT NULL CHECK (status IN ('pawned', 'picked_up', 'expired', 'sold')),
    client_number INTEGER REFERENCES client(client_number) ON DELETE SET NULL
  );
`;

export const createTicketIndexes = `
  CREATE INDEX IF NOT EXISTS idx_ticket_pawned_overdue_location_due_date
  ON ticket(location, due_date)
  WHERE status = 'pawned' AND is_overdue = TRUE;
`;
