export const createItemSubcategoryTable = `
  CREATE TABLE IF NOT EXISTS item_subcategory (
    id SERIAL PRIMARY KEY,
    category_id INTEGER NOT NULL REFERENCES item_category(id),
    name TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT item_subcategory_category_name_unique UNIQUE (category_id, name)
  );
`;

export const insertItemSubcategory = `
  INSERT INTO item_subcategory (category_id, name)
  SELECT c.id, v.name
  FROM (
    VALUES
      ('JEWELRY', 'ring'),
      ('JEWELRY', 'necklace'),
      ('JEWELRY', 'bracelet'),
      ('JEWELRY', 'chain'),
      ('JEWELRY', 'earrings'),
      ('JEWELRY', 'pendant'),
      ('JEWELRY', 'watch'),
      ('JEWELRY', 'gold scrap'),
      ('JEWELRY', 'other'),
      ('ELECTRONICS', 'phone'),
      ('ELECTRONICS', 'tablet'),
      ('ELECTRONICS', 'laptop'),
      ('ELECTRONICS', 'desktop'),
      ('ELECTRONICS', 'monitor'),
      ('ELECTRONICS', 'keyboard'),
      ('ELECTRONICS', 'mouse'),
      ('ELECTRONICS', 'gaming console'),
      ('ELECTRONICS', 'game'),
      ('ELECTRONICS', 'controller'),
      ('ELECTRONICS', 'headphone'),
      ('ELECTRONICS', 'earbuds'),
      ('ELECTRONICS', 'tv'),
      ('ELECTRONICS', 'camera'),
      ('ELECTRONICS', 'dvd player'),
      ('ELECTRONICS', 'dvd'),
      ('ELECTRONICS', 'other'),
      ('AUDIO EQUIPMENT', 'speaker'),
      ('AUDIO EQUIPMENT', 'subwoofer'),
      ('AUDIO EQUIPMENT', 'soundbar'),
      ('AUDIO EQUIPMENT', 'receiver'),
      ('AUDIO EQUIPMENT', 'microphone'),
      ('AUDIO EQUIPMENT', 'dj equipment'),
      ('AUDIO EQUIPMENT', 'other'),
      ('POWER TOOLS', 'drill'),
      ('POWER TOOLS', 'impact driver'),
      ('POWER TOOLS', 'saw'),
      ('POWER TOOLS', 'grinder'),
      ('POWER TOOLS', 'sander'),
      ('POWER TOOLS', 'nailer'),
      ('POWER TOOLS', 'stapler'),
      ('POWER TOOLS', 'other'),
      ('HAND TOOLS', 'hand tool'),
      ('HAND TOOLS', 'other'),
      ('UTILITY TOOLS', 'air compressor'),
      ('UTILITY TOOLS', 'pressure washer'),
      ('UTILITY TOOLS', 'generator'),
      ('UTILITY TOOLS', 'welder'),
      ('UTILITY TOOLS', 'jack'),
      ('UTILITY TOOLS', 'ladder'),
      ('UTILITY TOOLS', 'light'),
      ('UTILITY TOOLS', 'lawn mower'),
      ('UTILITY TOOLS', 'snow blower'),
      ('UTILITY TOOLS', 'trimmer'),
      ('UTILITY TOOLS', 'leaf blower'),
      ('UTILITY TOOLS', 'other'),
      ('DRYWALL TOOLS', 'screw gun'),
      ('DRYWALL TOOLS', 'stilts'),
      ('DRYWALL TOOLS', 'pump'),
      ('DRYWALL TOOLS', 'tube'),
      ('DRYWALL TOOLS', 'handle'),
      ('DRYWALL TOOLS', 'flusher'),
      ('DRYWALL TOOLS', 'roller'),
      ('DRYWALL TOOLS', 'other'),
      ('MUSICAL INSTRUMENTS', 'guitar'),
      ('MUSICAL INSTRUMENTS', 'bass'),
      ('MUSICAL INSTRUMENTS', 'keyboard'),
      ('MUSICAL INSTRUMENTS', 'drum'),
      ('MUSICAL INSTRUMENTS', 'cymbal'),
      ('MUSICAL INSTRUMENTS', 'violin'),
      ('MUSICAL INSTRUMENTS', 'flute'),
      ('MUSICAL INSTRUMENTS', 'saxophone'),
      ('MUSICAL INSTRUMENTS', 'amplifier'),
      ('MUSICAL INSTRUMENTS', 'audio interface'),
      ('MUSICAL INSTRUMENTS', 'other'),
      ('COLLECTIBLES', 'coin'),
      ('COLLECTIBLES', 'bill'),
      ('COLLECTIBLES', 'other'),
      ('SPORTS & OUTDOOR', 'bike'),
      ('SPORTS & OUTDOOR', 'golf'),
      ('SPORTS & OUTDOOR', 'fitness equipment'),
      ('SPORTS & OUTDOOR', 'punching bag'),
      ('SPORTS & OUTDOOR', 'camping gear'),
      ('SPORTS & OUTDOOR', 'fishing gear'),
      ('SPORTS & OUTDOOR', 'hunting gear'),
      ('SPORTS & OUTDOOR', 'hockey equipment'),
      ('SPORTS & OUTDOOR', 'knife'),
      ('SPORTS & OUTDOOR', 'other'),
      ('APPLIANCE', 'vacuum'),
      ('APPLIANCE', 'blender'),
      ('APPLIANCE', 'air fryer'),
      ('APPLIANCE', 'microwave'),
      ('APPLIANCE', 'coffee machine'),
      ('APPLIANCE', 'mixer'),
      ('APPLIANCE', 'fridge'),
      ('APPLIANCE', 'freezer'),
      ('APPLIANCE', 'other'),
      ('APPAREL', 'mukluk'),
      ('APPAREL', 'mitten'),
      ('APPAREL', 'boots'),
      ('APPAREL', 'beadwork'),
      ('APPAREL', 'other'),
      ('BABY & KIDS', 'stroller'),
      ('BABY & KIDS', 'baby monitor'),
      ('BABY & KIDS', 'toy'),
      ('BABY & KIDS', 'other')
  ) AS v(category_name, name)
  JOIN item_category c
    ON c.name = v.category_name
  WHERE NOT EXISTS (
    SELECT 1
    FROM item_subcategory s
    WHERE s.category_id = c.id
      AND s.name = v.name
  );
`;
